### ISSUE TITLE
Connection with Enterprise Manager cannot be established: PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by 62mkv** [oracle/docker-images#2079]
I am trying to follow https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/README.md#user-content-running-oracle-database-18c-express-edition-in-a-container

and when I try to connect to https://localhost:5500/em, I get 

```
Secure Connection Failed

An error occurred during a connection to localhost:5500. PR_END_OF_FILE_ERROR
```

error (FF browser) (the port, obviously, is mapped to the appropriate container)

When I try to debug this failure using `openssl` (under Win10), this is what I get: 

```
>openssl s_client -connect localhost:5500 -state
WARNING: can't open config file: /etc/ssl/openssl.cnf
CONNECTED(000001D0)
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
10468:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 307 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1629916600
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

not sure, if it's something with my PC or with the image. 

Here's what I do to reproduce: 

- clone <https://github.com/oracle/docker-images>
- cd to `OracleDatabase\SingleInstance\dockerfiles\18.4.0\` (this is chosen because it doesn't require to manually download Oracle binaries)
- run the following:

```cmd
docker build -t oracle/database:18.4.0-xe -f Dockerfile.xe .
```

- once image is built, use this .cmd to run it:

```cmd
docker run --name test-oracle-1 ^
--shm-size=1g ^
-p 1521:1521 ^
-p 5500:5500 ^
-e ORACLE_PWD=oracle ^
-v <PATH-to-mapped-data-folder>:/opt/oracle/oradata ^
oracle/database:18.4.0-xe
```

running this on Windows 10 x64, Docker Desktop 3.6.0 with WSL2 containers

**Comment by abhisbyk** [comment]
@62mkv Can u please try Oracle Database 21.3 XE image. This EM express connection failed issue is resolved in this image. Please reopen the issue if it persists in 21.3 XE image.

**Comment by jcrben** [comment]
It wasn't resolved for me until I ran what was suggested over at https://github.com/oracle/docker-images/issues/1419#issuecomment-689305485
